# Generated by Django 3.2.8 on 2021-10-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_rate', models.FloatField(default=0)),
                ('bid_price', models.FloatField(default=0)),
                ('ask_price', models.FloatField(default=0)),
                ('last_refreshed', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
